#ifndef QUARK_SYSCALLID_H
#define QUARK_SYSCALLID_H

typedef enum
{
    SYSCALL_TEST = 1,
    SYSCALL_MAP_ANON,
    SYSCALL_UNMAP_ANON,
    SYSCALL_MAP_PHYS,
    SYSCALL_UNMAP_PHYS,
    SYSCALL_OPEN_PORT,
    SYSCALL_CLOSE_PORT,
    SYSCALL_SEND_PID,
    SYSCALL_SEND_PORT,
    SYSCALL_RECEIVE,
    SYSCALL_CREATE_OBJECT,
    SYSCALL_AQUIRE_OBJECT,
    SYSCALL_RELEASE_OBJECT,
    SYSCALL_GET_PID,
    SYSCALL_CLONE,
    SYSCALL_SIGNAL_ACTION,
    SYSCALL_SIGNAL_RETURN,
    SYSCALL_SIGNAL_RAISE,
    SYSCALL_INTR_ACTION,
    SYSCALL_INTR_RETURN
} syscall_id_t;

#endif